name: jaga_jindan
description: 자가진단 자동화 앱

publish_to: 'none'

version: 0.2.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  path_provider: ^1.6.14
  fluttertoast: ^7.1.1
  http: ^0.12.2
  encrypt: ^4.0.2
  flutter_local_notifications: ^1.4.4+4
  url_launcher: ^5.6.0
  package_info: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
